name: docker-build

on:
  push:
    branches-ignore:
    - "renovate/**"
    paths:
    - "ubuntu/22.04/**"
    - ".github/workflows/docker-build.yml"
  pull_request:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
    paths:
    - "ubuntu/22.04/**"
    - ".github/workflows/docker-build.yml"
  workflow_dispatch:

jobs:
  build:
    name: docker-build
    permissions:
      packages: write
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: 22.04
    steps:

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
      with:
        context: ubuntu/22.04
        platforms: linux/amd64
        provenance: false
        sbom: false
        cache-from: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
